name: Bandit Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  bandit:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bandit
        run: |
          bandit -r . --format json --output bandit_report.json || true


      - name: Check for Bandit issues
        run: |
          if grep -q '"issue_severity": "HIGH"\|"issue_severity": "CRITICAL"' bandit_report.json; then
            echo "Bandit high or above security issues in the code."
            exit 1
          else
            echo "No issues found by Bandit."
          fi
